name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6

      - name: Install Dependencies
        run: |
          sudo apt install ffmpeg

      - name: Build the site
        run: |
          uv sync --dev
          uv run build-web --build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: /tmp/raylib_example_game_web_build/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1